application: horned-melon 
version: 1
runtime: php
api_version: 1

handlers:
- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /fonts
  static_dir: static/fonts

- url: /api
  script: api.php

- url: /kiwano
  script: kiwano.php

- url: /.*
  script: index.php
